language: node_js

node_js:
    - "6"
    - "5"
    - "4"
    - "iojs"
    - "node"
    #- "4.1"
    #- "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:
    # Prepare for automated tests
    - make automated-tests-prepare



script:
    # Check version and environment
    - make automated-tests-check

    # Run tests
    - make automated-tests-run



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/c72fe747115cfdb6cbbe

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
