language: node_js

node_js:
    - "node"
    - "6"
    - "5"
    - "4"
    #- "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



addons:
    apt:
        sources:
        - debian-sid    # Grab ShellCheck from the Debian repo
        packages:
        - shellcheck



env:
    - TEST_DIR=example/nodejs/



before_script:
    # Prepare for automated tests
    - make install



script:
    # Run tests
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
          - https://webhooks.gitter.im/e/c72fe747115cfdb6cbbe

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
